settings:
  update_interval: 150
  market_pairs:
    - BTC/USDT
    - ETH/USDT
    - LTC/USDT
    - ZIL/USDT
    - DOT/USDT
    - WAVES/USDT
    - ADA/USDT
    - ALGO/USDT
    - ETC/USDT

exchanges:
  binance:
    required:
      enabled: true

indicators:
    rsi:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1h
          period_count: 50
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 5m
          period_count: 14

informants:
    ema:
        - enabled: true
          signal:
            - ema
          candle_period: 1d
          period_count: 10
        - enabled: true
          signal:
            - ema
          candle_period: 1d
          period_count: 30