# Copy this file to config.yml to get started and then add your own configuration.
# Full documentation here: https://github.com/CryptoSignal/crypto-signal/blob/master/docs/config.md

settings:
  update_interval: 500
  market_pairs:
    - BTC/USDT
    - BCH/USDT
    - ETH/USDT
    - ETC/USDT
    - LTC/USDT
    - REN/USDT
    - ADA/USDT
    - SOL/USDT
    - BNB/USDT
    - ZIL/USDT
    - WAVES/USDT

exchanges:
    binance:
        required:
            enabled: true

indicators:
    rsi:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1h
          period_count: 50
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 20
          cold: 80
          candle_period: 5m
          period_count: 14


informants:
    bollinger_bands:
        - enabled: true
          signal:
            - upperband
          candle_period: 5m
        - enabled: true
          signal:
            - middleband
          candle_period: 5m
        - enabled: true
          signal:
            - lowerband
          candle_period: 5m
    ema:
        - enabled: true
          signal:
            - ema
          candle_period: 5m
          period_count: 10
        - enabled: true
          signal:
            - ema
          candle_period: 5m
          period_count: 20

crossovers:
    std_crossover:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: ema
          key_indicator_index: 0
          key_indicator_type: informants
          key_signal: ema
          crossed_indicator: ema
          crossed_indicator_index: 1
          crossed_indicator_type: informants
          crossed_signal: ema
        
notifiers:
    telegram:
        required:
            token: 4318021XXXX
            chat_id: -300XXXXXXX
        optional:
            parse_mode: html
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}" 